import { createPublicClient, createWalletClient, http, type Account, type Address, type Hex, type PublicClient, type TransactionReceipt, type WalletClient } from 'viem'
import { privateKeyToAccount, type PrivateKeyAccount } from 'viem/accounts'
import { somniaShannon } from '@somnia-chain/markets-sdk/chains'
import { SOMNIA_TESTNET_ADDRESSES } from '@somnia-chain/markets-sdk'

const erc20Abi=[{name:'balanceOf',type:'function',stateMutability:'view',inputs:[{name:'owner',type:'address'}],outputs:[{type:'uint256'}]},{name:'allowance',type:'function',stateMutability:'view',inputs:[{name:'owner',type:'address'},{name:'spender',type:'address'}],outputs:[{type:'uint256'}]},{name:'decimals',type:'function',stateMutability:'view',inputs:[],outputs:[{type:'uint8'}]},{name:'approve',type:'function',stateMutability:'nonpayable',inputs:[{name:'spender',type:'address'},{name:'amount',type:'uint256'}],outputs:[{type:'bool'}]}] as const

export interface ContractCall { to: Address; data: Hex; value?: bigint }
export interface Wallet { address:`0x${string}`; publicClient:PublicClient; balance():Promise<bigint>; tokenState(spender:Address):Promise<{balance:bigint;allowance:bigint;decimals:number}>; buildFiniteApproval(spender:Address,amount:bigint):Promise<ContractCall & {amount:bigint;gas:bigint}>; simulate(call:ContractCall):Promise<{ok:true}|{ok:false;error:string}>; estimate(call:ContractCall):Promise<bigint>; send(call:ContractCall):Promise<Hex>; receipt(hash:Hex):Promise<TransactionReceipt> }

export function createPrivateKeyWallet(key:`0x${string}`):Wallet {
  const account:PrivateKeyAccount=privateKeyToAccount(key), transport=http(somniaShannon.rpcUrls.default.http[0]), publicClient=createPublicClient({chain:somniaShannon,transport}), walletClient=createWalletClient({account,chain:somniaShannon,transport})
  return {address:account.address,publicClient,balance:()=>publicClient.getBalance({address:account.address}),tokenState:async(spender)=>{const token=SOMNIA_TESTNET_ADDRESSES.collateral!;const [balance,allowance,decimals]=await Promise.all([publicClient.readContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[account.address]}),publicClient.readContract({address:token,abi:erc20Abi,functionName:'allowance',args:[account.address,spender]}),publicClient.readContract({address:token,abi:erc20Abi,functionName:'decimals'})]);return {balance,allowance,decimals}},buildFiniteApproval:async(spender,amount)=>{const token=SOMNIA_TESTNET_ADDRESSES.collateral!;const data=await import('viem').then(v=>v.encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[spender,amount]}));const gas=await publicClient.estimateGas({account:account.address,to:token,data});return {to:token,data,amount,gas}},simulate:async(call)=>{try{await publicClient.call({account:account.address,...call});return {ok:true}}catch(error){return {ok:false,error:error instanceof Error?error.message:String(error)}}},estimate:(call)=>publicClient.estimateGas({account:account.address,...call}),send:(call)=>walletClient.sendTransaction({account,...call}),receipt:(hash)=>publicClient.waitForTransactionReceipt({hash})}
}
